In [5]:
import os, sys, importlib, pathlib
import pandas as pd
from pathlib import Path
sys.path.append (os.path.abspath(".."))
# my utils
from utils import fa
from utils import modeling
from utils import preprocess_listings

# 标准版存档V0：

LABELS_EN=[
            'open to different cultures', 'cosmopolitan','international view', 'cultural exchange',
            'personal life', 'life experiences', 'divers interests', 'hobbies', 'enjoy life',
            'meet new people', 'welcoming', 'friendly', 'sociable', 'interpersonal interaction',
            'thoughtful service', 'attentive to needs', 'willing to help', 'responsive',
            'fan of Airbnb', 'Airbnb community','love Airbnb', 'travel with Airbnb'
        ]
DICT_FACTOR_ITEMS={"ouverture":['open to different cultures', 'cosmopolitan','international view', 'cultural exchange'],
                   "authenticité":['personal life', 'life experiences', 'divers interests', 'hobbies', 'enjoy life'],
                   "sociabilité":['meet new people', 'welcoming', 'friendly', 'sociable', 'interpersonal interaction'],
                   "auto_promotion":['thoughtful service', 'attentive to needs', 'willing to help', 'responsive'],
                   "exemplarité":['fan of Airbnb', 'Airbnb community','love Airbnb', 'travel with Airbnb']}

In [6]:
path_df="../data_processed\listings_tactics_bio_vis-paris_london-2306_2406.csv"
df_all=pd.read_csv(path_df)
print(df_all.shape)

C:\Users\yeliu\AppData\Local\Temp\ipykernel_8772\3453220627.py:2: DtypeWarning: Columns (68) have mixed types. Specify dtype option on import or set low_memory=False.
  df_all=pd.read_csv(path_df)

(187851, 124)

In [8]:
df_all.columns.to_list()

['id',
 'listing_url',
 'scrape_id',
 'last_scraped',
 'source',
 'name',
 'description',
 'neighborhood_overview',
 'picture_url',
 'host_id',
 'host_url',
 'host_name',
 'host_since',
 'host_location',
 'host_about',
 'host_response_time',
 'host_response_rate',
 'host_acceptance_rate',
 'host_is_superhost',
 'host_thumbnail_url',
 'host_picture_url',
 'host_neighbourhood',
 'host_listings_count',
 'host_total_listings_count',
 'host_verifications',
 'host_has_profile_pic',
 'host_identity_verified',
 'neighbourhood',
 'neighbourhood_cleansed',
 'neighbourhood_group_cleansed',
 'latitude',
 'longitude',
 'property_type',
 'room_type',
 'accommodates',
 'bathrooms',
 'bathrooms_text',
 'bedrooms',
 'beds',
 'amenities',
 'price',
 'minimum_nights',
 'maximum_nights',
 'minimum_minimum_nights',
 'maximum_minimum_nights',
 'minimum_maximum_nights',
 'maximum_maximum_nights',
 'minimum_nights_avg_ntm',
 'maximum_nights_avg_ntm',
 'calendar_updated',
 'has_availability',
 'availability_30',
 'availability_60',
 'availability_90',
 'availability_365',
 'calendar_last_scraped',
 'number_of_reviews_till_Q',
 'number_of_reviews_ltm',
 'number_of_reviews_l30d',
 'first_review',
 'last_review',
 'review_scores_rating',
 'review_scores_accuracy',
 'review_scores_cleanliness',
 'review_scores_checkin',
 'review_scores_communication',
 'review_scores_location',
 'review_scores_value',
 'license',
 'instant_bookable',
 'calculated_host_listings_count',
 'calculated_host_listings_count_entire_homes',
 'calculated_host_listings_count_private_rooms',
 'calculated_host_listings_count_shared_rooms',
 'reviews_per_month',
 'number_of_reviews_till_nextQ',
 'number_of_reviews_nextQ',
 'booking_rate_l90d',
 'is_within_1km',
 'has_rating',
 'years_since_host',
 'has_since',
 'lang',
 'len',
 'has_response_rate',
 'professional_host',
 'open to different cultures',
 'cosmopolitan',
 'international view',
 'cultural exchange',
 'personal life',
 'life experiences',
 'divers interests',
 'hobbies',
 'enjoy life',
 'meet new people',
 'welcoming',
 'friendly',
 'sociable',
 'interpersonal interaction',
 'thoughtful service',
 'attentive to needs',
 'willing to help',
 'responsive',
 'fan of Airbnb',
 'Airbnb community',
 'love Airbnb',
 'travel with Airbnb',
 'is_paris',
 'in_2024',
 'ouverture',
 'authenticité',
 'sociabilité',
 'auto_promotion',
 'exemplarité',
 'has_face',
 'bbox_list',
 'host_picture_type',
 'age',
 'age_class',
 'gender',
 'smile_score',
 'is_smiling',
 'dominant_emotion']

In [10]:
# drop no pic match?
df=df_all.copy()
print(df[['host_has_profile_pic', 'has_face']].value_counts(dropna=False),"\n")
df=df[df["has_face"].notna()]
print(len(df_all),len(df))

host_has_profile_pic  has_face
t                     1.0         123800
                      0.0          55515
f                     NaN           7264
t                     NaN           1271
f                     0.0              1
Name: count, dtype: int64

187851 179316

In [ ]:
vars_tactics=[
    "ouverture", "authenticité","sociabilité","auto_promotion","exemplarité", 
    "host_picture_type","is_smiling", "smile_score"
    ]
df[vars_tactics].value_counts(dropna=False)
df[vars_tactics]=df[vars_tactics].fillna(0)

# vars_person=["age_class","gender"]
# df[vars_person]=df[vars_person].fillna('unk')

## ols:

In [16]:
df[(df['is_paris']==1)&(df['in_2024']==0)]

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,exemplarité,has_face,bbox_list,host_picture_type,age,age_class,gender,smile_score,is_smiling,dominant_emotion
92212,153674,https://www.airbnb.com/rooms/153674,20230606220143,2023-06-07,city scrape,Rental unit in Paris · ★4.44 · 1 bedroom · 3 b...,"Ideally located in the heart of Paris, in a li...","Staying in the 10th arrondissement, between th...",https://a0.muscache.com/pictures/prohost-api/H...,739021,...,0.010267,1.0,"[[79, 48, 148, 142]]",pro_style,47.0,middle,Woman,99.420952,1.0,happy
92213,5396,https://www.airbnb.com/rooms/5396,20230606220143,2023-06-08,previous scrape,Rental unit in Paris · ★4.55 · Studio · 1 bed ...,"Cozy, well-appointed and graciously designed s...","You are within walking distance to the Louvre,...",https://a0.muscache.com/pictures/52413/f9bf76f...,7903,...,-0.154413,1.0,"[[141, 38, 206, 124], [72, 14, 132, 96]]",life_style,29.0,young,multi,97.692505,1.0,happy
92214,154292,https://www.airbnb.com/rooms/154292,20230606220143,2023-06-07,city scrape,Rental unit in Paris · ★4.62 · 1 bedroom · 1 b...,"Nice flat designed by an architect, in an area...","Charming authentic parisian neighborhood, with...",https://a0.muscache.com/pictures/bfc84997-6491...,137719,...,-0.751471,1.0,"[[88, 62, 152, 146]]",pro_style,26.0,young,Man,0.000939,0.0,neutral
92215,7397,https://www.airbnb.com/rooms/7397,20230606220143,2023-06-08,city scrape,Rental unit in Paris · ★4.72 · 2 bedrooms · 2 ...,"VERY CONVENIENT, WITH THE BEST LOCATION !<br /...",NaN,https://a0.muscache.com/pictures/67928287/330b...,2626,...,-0.709955,1.0,"[[50, 47, 157, 192]]",pro_style,40.0,middle,Man,0.063789,0.0,angry
92216,33814,https://www.airbnb.com/rooms/33814,20230606220143,2023-06-07,city scrape,Rental unit in Paris · ★4.36 · 1 bedroom · 2 b...,"70m2, confortable, clean, quiet, very bright a...","In the neighborhood, you find both big streets...",https://a0.muscache.com/pictures/190719/da5f80...,146066,...,1.229936,0.0,[],no_person,NaN,NaN,NaN,0.000000,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125108,907876483956947091,https://www.airbnb.com/rooms/907876483956947091,20230606220143,2023-06-07,city scrape,Rental unit in Gentilly · ★New · 1 bedroom · 1...,Bel appartement de 30m2. <br />Il se compose d...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,51193419,...,0.000000,1.0,"[[80, 45, 151, 146]]",pro_style,26.0,young,Man,99.821266,1.0,happy
125109,907889552689420357,https://www.airbnb.com/rooms/907889552689420357,20230606220143,2023-06-08,city scrape,Rental unit in Paris · ★New · 1 bedroom · 1 be...,This modern one-bedroom apartment in the 19th ...,The 19th arrondissement in Paris holds down th...,https://a0.muscache.com/pictures/prohost-api/H...,518556594,...,-0.256635,0.0,[],no_person,NaN,NaN,NaN,0.000000,0.0,NaN
125110,907921757183609134,https://www.airbnb.com/rooms/907921757183609134,20230606220143,2023-06-07,city scrape,Rental unit in Paris · ★New · 1 bedroom · 2 be...,Notre mission est de permettre aux individus d...,NaN,https://a0.muscache.com/pictures/prohost-api/H...,489964484,...,0.000000,0.0,[],no_person,NaN,NaN,NaN,0.000000,0.0,NaN
125111,907922174138736701,https://www.airbnb.com/rooms/907922174138736701,20230606220143,2023-06-07,city scrape,Rental unit in Paris · ★New · 1 bedroom · 2 be...,Notre mission est de permettre aux individus d...,NaN,https://a0.muscache.com/pictures/prohost-api/H...,489964484,...,0.000000,0.0,[],no_person,NaN,NaN,NaN,0.000000,0.0,NaN
125112,907924863916056172,https://www.airbnb.com/rooms/907924863916056172,20230606220143,2023-06-07,city scrape,Rental unit in Paris · ★New · 2 bedrooms · 3 b...,This modern two-bedroom apartment in the 11th ...,This is a great location to explore the city o...,https://a0.muscache.com/pictures/prohost-api/H...,518568140,...,-0.256635,0.0,[],no_person,NaN,NaN,NaN,0.000000,0.0,NaN

In [35]:
importlib.reload(modeling)
from utils.modeling import write_formula,build_model

import statsmodels.api as sm
import statsmodels.formula.api as smf


# C(host_is_superhost)
# C(host_has_profile_pic)

x_vars=["host_identity_verified", "host_has_profile_pic",         
    "review_scores_rating", #"has_rating", "number_of_reviews",
    "years_since_host","professional_host",'host_is_superhost', ##'calculated_host_listings_count',
    # 'status_changed', 'old_host_sp_changed',# "is_changed"
    "lang", "len",
    "price",
    "availability_90",#*
    "room_type", "instant_bookable", #'is_within_1km',
    
    "ouverture", "authenticité","sociabilité","auto_promotion","exemplarité", 
    "host_picture_type","is_smiling"
]  
tactics_vars=["is_paris","in_2024"]


formula= ("booking_rate_l90d ~ C(host_identity_verified)  + review_scores_rating + has_rating + "
            "C(host_is_superhost) +"
            "years_since_host + professional_host + "
            "len + C(lang) +"
            "price  + availability_90 + C(room_type) + C(instant_bookable) + "
            "(ouverture + authenticité + sociabilité + auto_promotion + exemplarité)*is_paris+"
            "C(host_picture_type) + is_smiling "
            # smile_score coef 过小!
            # "is_paris "
)
df_ols=df[df['in_2024']==1]
model=smf.ols(formula, data=df_ols).fit()
summary=model.summary()
print(summary)

                            OLS Regression Results
==============================================================================
Dep. Variable:      booking_rate_l90d   R-squared:                       0.259
Model:                            OLS   Adj. R-squared:                  0.258
Method:                 Least Squares   F-statistic:                     1241.
Date:                Sun, 29 Mar 2026   Prob (F-statistic):               0.00
Time:                        20:00:05   Log-Likelihood:                 41644.
No. Observations:              106812   AIC:                        -8.323e+04
Df Residuals:                  106781   BIC:                        -8.293e+04
Df Model:                          30
Covariance Type:            nonrobust
=====================================================================================================
                                        coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------
Intercept                             0.1162      0.008     14.134      0.000       0.100       0.132
C(host_identity_verified)[T.t]        0.0160      0.002      7.902      0.000       0.012       0.020
C(host_is_superhost)[T.t]             0.0562      0.001     43.951      0.000       0.054       0.059
C(lang)[T.fr]                         0.0012      0.002      0.613      0.540      -0.003       0.005
C(lang)[T.no_text]                   -0.0031      0.001     -2.120      0.034      -0.006      -0.000
C(lang)[T.other_langs]                0.0071      0.005      1.386      0.166      -0.003       0.017
C(room_type)[T.Hotel room]           -0.0468      0.007     -6.734      0.000      -0.060      -0.033
C(room_type)[T.Private room]          0.0246      0.001     17.576      0.000       0.022       0.027
C(room_type)[T.Shared room]           0.0317      0.008      3.987      0.000       0.016       0.047
C(instant_bookable)[T.t]              0.0160      0.001     12.719      0.000       0.014       0.018
C(host_picture_type)[T.no_person]    -0.0068      0.002     -4.491      0.000      -0.010      -0.004
C(host_picture_type)[T.pro_style]     0.0036      0.001      2.993      0.003       0.001       0.006
review_scores_rating                  0.0188      0.002     12.146      0.000       0.016       0.022
has_rating                            0.0549      0.001     44.843      0.000       0.053       0.057
years_since_host                     -0.0024      0.000    -15.682      0.000      -0.003      -0.002
professional_host                     0.0014      0.001      1.157      0.247      -0.001       0.004
len                                3.387e-06    1.2e-05      0.282      0.778   -2.02e-05    2.69e-05
price                             -4.071e-06   6.49e-07     -6.278      0.000   -5.34e-06    -2.8e-06
availability_90                      -0.0030   2.01e-05   -148.034      0.000      -0.003      -0.003
ouverture                             0.0022      0.001      1.592      0.111      -0.000       0.005
authenticité                          0.0049      0.001      3.679      0.000       0.002       0.008
sociabilité                           0.0098      0.001      7.768      0.000       0.007       0.012
auto_promotion                       -0.0041      0.001     -3.017      0.003      -0.007      -0.001
exemplarité                           0.0064      0.001      5.148      0.000       0.004       0.009
is_paris                             -0.0311      0.001    -24.153      0.000      -0.034      -0.029
ouverture:is_paris                   -0.0070      0.002     -3.697      0.000      -0.011      -0.003
authenticité:is_paris                -0.0038      0.002     -2.050      0.040      -0.007      -0.000
sociabilité:is_paris                 -0.0046      0.002     -2.601      0.009      -0.008      -0.001
auto_promotion:is_paris               0.0048      0.002      2.581      0.010       0.001       0.008
exemplarité:is_paris                 -0.0080      0.002     -4.682      0.000      -0.011      -0.005
is_smiling                           -0.0026      0.001     -2.116      0.034      -0.005      -0.000
==============================================================================
Omnibus:                    54876.907   Durbin-Watson:                   1.961
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           403804.807
Skew:                           2.396   Prob(JB):                         0.00
Kurtosis:                      11.232   Cond. No.                     1.37e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.37e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

In [58]:
# subdf=df[df['in_2024']==1]
# print(subdf[['is_paris','in_2024']].value_counts(dropna=False))
# formula= ("booking_rate_l90d ~ C(host_identity_verified)  + C(lang) + C(room_type) + C(instant_bookable) + + review_scores_rating + has_rating + years_since_host + professional_host + len + price + availability_90 + "
#         "C(host_is_superhost) + ouverture + authenticité + sociabilité + auto_promotion + exemplarité +  C(host_picture_type) + is_smiling + "
#         # smile_score coef 过小!
#         "is_paris "
#         # "in_2024"
        
# )
# model=smf.ols(formula, data=subdf).fit()
# summary=model.summary()
# print(summary)

In [68]:
formula= ("is_smiling ~ C(host_identity_verified) + C(host_has_profile_pic) + C(host_is_superhost) + C(lang) + C(room_type) + C(instant_bookable) + review_scores_rating + has_rating + years_since_host + professional_host + len + price + availability_90 + "
        # "ouverture + authenticité + sociabilité + auto_promotion + exemplarité + is_smiling +  C(host_picture_type)+"
        # smile_score coef 过小!
        "is_paris * in_2024"
)
model=smf.ols(formula, data=df).fit()
summary=model.summary()
print(summary)

                            OLS Regression Results
==============================================================================
Dep. Variable:             is_smiling   R-squared:                       0.060
Model:                            OLS   Adj. R-squared:                  0.060
Method:                 Least Squares   F-statistic:                     569.9
Date:                Mon, 23 Mar 2026   Prob (F-statistic):               0.00
Time:                        22:12:28   Log-Likelihood:            -1.0712e+05
No. Observations:              179316   AIC:                         2.143e+05
Df Residuals:                  179295   BIC:                         2.145e+05
Df Model:                          20
Covariance Type:            nonrobust
==================================================================================================
                                     coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                         -0.3840      0.440     -0.873      0.383      -1.246       0.478
C(host_identity_verified)[T.t]    -0.0037      0.004     -0.872      0.383      -0.012       0.005
C(host_has_profile_pic)[T.t]       0.3951      0.440      0.898      0.369      -0.467       1.257
C(host_is_superhost)[T.t]          0.0438      0.003     15.909      0.000       0.038       0.049
C(lang)[T.fr]                      0.0376      0.004     10.064      0.000       0.030       0.045
C(lang)[T.no_text]                 0.0265      0.003      9.362      0.000       0.021       0.032
C(lang)[T.other_langs]            -0.0365      0.010     -3.497      0.000      -0.057      -0.016
C(room_type)[T.Hotel room]        -0.0683      0.012     -5.682      0.000      -0.092      -0.045
C(room_type)[T.Private room]       0.0399      0.003     14.677      0.000       0.035       0.045
C(room_type)[T.Shared room]        0.0192      0.016      1.201      0.230      -0.012       0.051
C(instant_bookable)[T.t]          -0.0629      0.003    -25.097      0.000      -0.068      -0.058
review_scores_rating               0.0532      0.003     19.412      0.000       0.048       0.059
has_rating                         0.0226      0.003      8.613      0.000       0.017       0.028
years_since_host                   0.0150      0.000     46.301      0.000       0.014       0.016
professional_host                 -0.0998      0.002    -41.787      0.000      -0.104      -0.095
len                            -1.755e-05    2.1e-05     -0.838      0.402   -5.86e-05    2.35e-05
price                          -7.667e-06    1.5e-06     -5.103      0.000   -1.06e-05   -4.72e-06
availability_90                   -0.0009   4.06e-05    -23.046      0.000      -0.001      -0.001
is_paris                          -0.0569      0.004    -15.917      0.000      -0.064      -0.050
in_2024                            0.0009      0.003      0.282      0.778      -0.005       0.007
is_paris:in_2024                   0.0438      0.004     10.193      0.000       0.035       0.052
==============================================================================
Omnibus:                    70916.712   Durbin-Watson:                   1.979
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            28478.491
Skew:                           0.822   Prob(JB):                         0.00
Kurtosis:                       1.948   Cond. No.                     4.43e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.43e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

In [6]:
importlib.reload(modeling)
from utils.modeling import modeling_main,build_model

#-------------------------------vars------------------------------------

x_vars=["host_identity_verified", "host_has_profile_pic",         
    "review_scores_rating", #"has_rating", "number_of_reviews",
    "years_since_host","professional_host",'host_is_superhost', ##'calculated_host_listings_count',
    # 'status_changed', 'old_host_sp_changed',# "is_changed"
    "lang", "len",
    "price",
    "availability_90",#*
    "room_type", "instant_bookable", #'is_within_1km',
    
    "ouverture", "authenticité","sociabilité","auto_promotion","exemplarité", 
    "host_picture_type","is_smiling"
]  
tactics_vars=["is_paris","in_2024"]

modeling_main(df_input=df_all, 
            x_vars=x_vars, 
            y_var="booking_rate_l90d", 
            key_vars=tactics_vars, 
            group_col=None,#"host_is_superhost',#==stauts_changed+sp_changed
            output_folder=None,
            to_fillna0=True,
            run_vif=True,
            # save_models_summary=False,  
            save_models_table=False,
            save_plots=False,
            ndigits=4
        )

=============================================check data=============================================
[INFO] fillna in key cols!`

========================================check output folder=========================================
================================================vif=================================================
+key_vars ; - group_cols
remove key_vars in x_vars
Final x_vars_ctrl :['host_identity_verified', 'host_has_profile_pic', 'review_scores_rating', 'years_since_host', 'professional_host', 'host_is_superhost', 'lang', 'len', 'price', 'availability_90', 'room_type', 'instant_bookable', 'ouverture', 'authenticité', 'sociabilité', 'auto_promotion', 'exemplarité', 'host_picture_type', 'is_smiling']

[INFO] formula :
 booking_rate_l90d ~ C(host_identity_verified) + C(host_has_profile_pic) + C(host_is_superhost) + C(lang) + C(room_type) + C(instant_bookable) + C(host_picture_type) + review_scores_rating + years_since_host + professional_host + len + price + availability_90 + ouverture + authenticité + sociabilité + auto_promotion + exemplarité + is_smiling+ is_paris + in_2024

                            Variables           VIF Niveau_colinearite
0                           Intercept  91561.521721                ***
1      C(host_identity_verified)[T.t]      1.017968                  *
2        C(host_has_profile_pic)[T.t]      1.000178                  *
3           C(host_is_superhost)[T.t]      1.095642                  *
4                       C(lang)[T.fr]      1.926281                  *
5                  C(lang)[T.no_text]      1.008223                  *
6              C(lang)[T.other_langs]      1.038891                  *
7          C(room_type)[T.Hotel room]      1.042722                  *
8        C(room_type)[T.Private room]      1.167226                  *
9         C(room_type)[T.Shared room]      1.007452                  *
10           C(instant_bookable)[T.t]      1.236604                  *
11  C(host_picture_type)[T.no_person]      2.001945                  *
12  C(host_picture_type)[T.pro_style]      1.374454                  *
13               review_scores_rating      1.081602                  *
14                   years_since_host      1.225022                  *
15                  professional_host      1.384001                  *
16                                len      1.292234                  *
17                              price      1.030346                  *
18                    availability_90      1.103914                  *
19                          ouverture      1.497843                  *
20                       authenticité      1.871723                  *
21                        sociabilité      1.543139                  *
22                     auto_promotion      2.115015                  *
23                        exemplarité      1.366204                  *
24                         is_smiling      1.247044                  *
25                           is_paris      1.955936                  *
26                            in_2024      1.069476                  *

 ============================================basic model=============================================

[NUMBER CHECK1] x_vars:19, x_vars_ctrl:19
['host_identity_verified', 'host_has_profile_pic', 'review_scores_rating', 'years_since_host', 'professional_host', 'host_is_superhost', 'lang', 'len', 'price', 'availability_90', 'room_type', 'instant_bookable', 'ouverture', 'authenticité', 'sociabilité', 'auto_promotion', 'exemplarité', 'host_picture_type', 'is_smiling', 'booking_rate_l90d']
-key_vars ; - group_cols
Final x_vars_ctrl :['host_identity_verified', 'host_has_profile_pic', 'review_scores_rating', 'years_since_host', 'professional_host', 'host_is_superhost', 'lang', 'len', 'price', 'availability_90', 'room_type', 'instant_bookable', 'ouverture', 'authenticité', 'sociabilité', 'auto_promotion', 'exemplarité', 'host_picture_type', 'is_smiling']

[INFO] formula :
 booking_rate_l90d ~ C(host_identity_verified) + C(host_has_profile_pic) + C(host_is_superhost) + C(lang) + C(room_type) + C(instant_bookable) + C(host_picture_type) + review_scores_rating + years_since_host + professional_host + len + price + availability_90 + ouverture + authenticité + sociabilité + auto_promotion + exemplarité + is_smiling

[NUMBER CHECK2] x_vars:19, x_vars_ctrl:19
                            OLS Regression Results
==============================================================================
Dep. Variable:      booking_rate_l90d   R-squared:                       0.293
Model:                            OLS   Adj. R-squared:                  0.292
Method:                 Least Squares   F-statistic:                     1573.
Date:                Mon, 23 Mar 2026   Prob (F-statistic):               0.00
Time:                        14:14:12   Log-Likelihood:                 13477.
No. Observations:               91337   AIC:                        -2.690e+04
Df Residuals:                   91312   BIC:                        -2.667e+04
Df Model:                          24
Covariance Type:            nonrobust
=====================================================================================================
                                        coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------
Intercept                             0.3071      0.209      1.469      0.142      -0.103       0.717
C(host_identity_verified)[T.t]        0.0335      0.003     10.952      0.000       0.027       0.039
C(host_has_profile_pic)[T.t]         -0.0051      0.209     -0.025      0.980      -0.414       0.404
C(host_is_superhost)[T.t]             0.0628      0.002     36.626      0.000       0.059       0.066
C(lang)[T.fr]                        -0.0038      0.002     -2.232      0.026      -0.007      -0.000
C(lang)[T.no_text]                    0.0335      0.025      1.338      0.181      -0.016       0.083
C(lang)[T.other_langs]                0.0279      0.006      4.718      0.000       0.016       0.039
C(room_type)[T.Hotel room]           -0.0288      0.007     -3.940      0.000      -0.043      -0.014
C(room_type)[T.Private room]          0.0622      0.002     34.955      0.000       0.059       0.066
C(room_type)[T.Shared room]           0.0557      0.011      5.003      0.000       0.034       0.077
C(instant_bookable)[T.t]              0.0185      0.002     11.073      0.000       0.015       0.022
C(host_picture_type)[T.no_person]    -0.0139      0.002     -6.598      0.000      -0.018      -0.010
C(host_picture_type)[T.pro_style]     0.0019      0.002      1.101      0.271      -0.001       0.005
review_scores_rating                  0.0030      0.002      1.594      0.111      -0.001       0.007
years_since_host                     -0.0020      0.000     -8.784      0.000      -0.002      -0.002
professional_host                    -0.0056      0.002     -3.461      0.001      -0.009      -0.002
len                               -1.821e-06   1.11e-05     -0.164      0.869   -2.35e-05    1.99e-05
price                              -1.06e-05    1.2e-06     -8.839      0.000    -1.3e-05   -8.25e-06
availability_90                      -0.0046   2.67e-05   -171.687      0.000      -0.005      -0.005
ouverture                            -0.0032      0.001     -3.476      0.001      -0.005      -0.001
authenticité                          0.0049      0.001      5.266      0.000       0.003       0.007
sociabilité                           0.0105      0.001     11.887      0.000       0.009       0.012
auto_promotion                       -0.0029      0.001     -2.862      0.004      -0.005      -0.001
exemplarité                           0.0049      0.001      5.834      0.000       0.003       0.007
is_smiling                           -0.0057      0.002     -3.366      0.001      -0.009      -0.002
==============================================================================
Omnibus:                    25280.622   Durbin-Watson:                   1.909
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            67579.057
Skew:                           1.494   Prob(JB):                         0.00
Kurtosis:                       5.972   Cond. No.                     2.73e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.73e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

 ===========================================tactics model============================================

[NUMBER CHECK1] x_vars:19, x_vars_ctrl:19
['host_identity_verified', 'host_has_profile_pic', 'review_scores_rating', 'years_since_host', 'professional_host', 'host_is_superhost', 'lang', 'len', 'price', 'availability_90', 'room_type', 'instant_bookable', 'ouverture', 'authenticité', 'sociabilité', 'auto_promotion', 'exemplarité', 'host_picture_type', 'is_smiling', 'booking_rate_l90d', 'is_paris', 'in_2024']
+key_vars ; - group_cols
remove key_vars in x_vars
Final x_vars_ctrl :['host_identity_verified', 'host_has_profile_pic', 'review_scores_rating', 'years_since_host', 'professional_host', 'host_is_superhost', 'lang', 'len', 'price', 'availability_90', 'room_type', 'instant_bookable', 'ouverture', 'authenticité', 'sociabilité', 'auto_promotion', 'exemplarité', 'host_picture_type', 'is_smiling']

[INFO] formula :
 booking_rate_l90d ~ C(host_identity_verified) + C(host_has_profile_pic) + C(host_is_superhost) + C(lang) + C(room_type) + C(instant_bookable) + C(host_picture_type) + review_scores_rating + years_since_host + professional_host + len + price + availability_90 + ouverture + authenticité + sociabilité + auto_promotion + exemplarité + is_smiling+ is_paris + in_2024

[NUMBER CHECK2] x_vars:19, x_vars_ctrl:19
                            OLS Regression Results
==============================================================================
Dep. Variable:      booking_rate_l90d   R-squared:                       0.307
Model:                            OLS   Adj. R-squared:                  0.306
Method:                 Least Squares   F-statistic:                     1553.
Date:                Mon, 23 Mar 2026   Prob (F-statistic):               0.00
Time:                        14:14:15   Log-Likelihood:                 14394.
No. Observations:               91337   AIC:                        -2.873e+04
Df Residuals:                   91310   BIC:                        -2.848e+04
Df Model:                          26
Covariance Type:            nonrobust
=====================================================================================================
                                        coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------
Intercept                             0.3532      0.207      1.706      0.088      -0.052       0.759
C(host_identity_verified)[T.t]        0.0304      0.003     10.049      0.000       0.024       0.036
C(host_has_profile_pic)[T.t]         -0.0337      0.207     -0.163      0.871      -0.439       0.372
C(host_is_superhost)[T.t]             0.0731      0.002     42.625      0.000       0.070       0.076
C(lang)[T.fr]                         0.0040      0.002      1.869      0.062      -0.000       0.008
C(lang)[T.no_text]                    0.0379      0.025      1.525      0.127      -0.011       0.087
C(lang)[T.other_langs]                0.0220      0.006      3.753      0.000       0.011       0.033
C(room_type)[T.Hotel room]           -0.0431      0.007     -5.950      0.000      -0.057      -0.029
C(room_type)[T.Private room]          0.0573      0.002     31.715      0.000       0.054       0.061
C(room_type)[T.Shared room]           0.0505      0.011      4.587      0.000       0.029       0.072
C(instant_bookable)[T.t]              0.0210      0.002     12.692      0.000       0.018       0.024
C(host_picture_type)[T.no_person]    -0.0122      0.002     -5.864      0.000      -0.016      -0.008
C(host_picture_type)[T.pro_style]     0.0024      0.002      1.469      0.142      -0.001       0.006
review_scores_rating                  0.0065      0.002      3.530      0.000       0.003       0.010
years_since_host                     -0.0025      0.000    -11.311      0.000      -0.003      -0.002
professional_host                    -0.0083      0.002     -5.060      0.000      -0.011      -0.005
len                               -2.264e-05    1.1e-05     -2.055      0.040   -4.42e-05   -1.04e-06
price                             -1.168e-05   1.19e-06     -9.831      0.000    -1.4e-05   -9.35e-06
availability_90                      -0.0044   2.67e-05   -165.336      0.000      -0.004      -0.004
ouverture                            -0.0015      0.001     -1.684      0.092      -0.003       0.000
authenticité                          0.0045      0.001      4.767      0.000       0.003       0.006
sociabilité                           0.0093      0.001     10.658      0.000       0.008       0.011
auto_promotion                       -0.0018      0.001     -1.799      0.072      -0.004       0.000
exemplarité                           0.0048      0.001      5.681      0.000       0.003       0.006
is_smiling                           -0.0042      0.002     -2.481      0.013      -0.007      -0.001
is_paris                             -0.0035      0.002     -1.802      0.071      -0.007       0.000
in_2024                              -0.0613      0.001    -42.822      0.000      -0.064      -0.058
==============================================================================
Omnibus:                    24668.410   Durbin-Watson:                   1.944
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            64843.084
Skew:                           1.464   Prob(JB):                         0.00
Kurtosis:                       5.909   Cond. No.                     2.73e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.73e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

 ============================================models table============================================

TypeError: 'in <string>' requires string as left operand, not NoneType